import type { Metadata } from "next";
import { poppins } from "@/components/Fonts";
import { CartProvider } from "./CartContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
          <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
